version: '3.8'

services:
  db:
    build:
      context: ./postgresql_psycopg2_database
    container_name: invoice-generator-postgres-container
    ports:
      - "5432:5432"
    networks:
      - invoice-network

  web:
    build:
      context: .
    container_name: invoice-generator-app-container
    ports:
      - "8200:8200"
    networks:
      - invoice-network
    depends_on:
      - db 

networks:
  invoice-network:
    driver: bridge
