version: '3.8'

services:
  db:
    build:
      context: ./postgresql_psycopg2_database
    container_name: invoice-generator-postgres-container
    ports:
      - "5432:5432"
    networks:
      - invoice-network

  web:
    build:
      context: .
    container_name: invoice-generator-app
    ports:
      - "8200:8200"
    networks:
      - invoice-network
    depends_on:
      - db 
    entrypoint: /entrypoint.sh
    command: ["python", "manage.py", "runserver", "0.0.0.0:8200"]

networks:
  invoice-network:
    driver: bridge
