version: '3.8'

services:
  db:
    build:
      context: ./postgresql_psycopg2_database
    container_name: invoice-generator-postgres-container
    ports:
      - "5432:5432"
    networks:
      - invoice-network



  web:
    build:
      context: .
    container_name: invoice-generator-app-container
    ports:
      - "8200:8200"
    networks:
      - invoice-network
    depends_on:
      - db 

  nginx:
    build:
      context: ./nginx-docker
    container_name: nginx-container
    ports:
      - "80:80"
    networks:
      - invoice-network
    depends_on:
      - web
    volumes:
      - ./nginx-docker/html:/usr/share/nginx/html  # Ensure this points to your website files
      
networks:
  invoice-network:
    driver: bridge

# --------------------------------------------------------------------
# version: '3.8'

# services:
#   db:
#     build:
#       context: ./postgresql_psycopg2_database
#     container_name: invoice-generator-postgres-container
#     ports:
#       - "5432:5432"
#     networks:
#       - invoice-network
#     volumes:
#       - ./postgres-data:/var/lib/postgresql/data
#     depends_on:
#       - postgres-data

#   web:
#     build:
#       context: .
#     container_name: invoice-generator-app-container
#     ports:
#       - "8200:8200"
#     networks:
#       - invoice-network
#     depends_on:
#       - db 

# networks:
#   invoice-network:
#     driver: bridge

# volumes:
#   postgres-data:
#     driver: local
