
pipeline{

    agent any

environment {
        // Define environment variables
        SONAR_HOME = tool name: "invoice-SonarQube"
    }
    
           options {
        timeout(time: 5, unit: 'MINUTES') // Setting a timeout for the entire pipeline
    }

    stages{
        stage("Checkout Code from Github"){
            steps{
                git url: "https://github.com/localhost.git",branch: "Devops"
            }
        }
        stage("Build"){
            steps{
                echo "This is build"
            }
        }
        stage("Test"){
            steps{
                echo "This is Test"
            }
        }
        stage("Deploy"){
            steps{
                echo "This is Deploy"
            }
        }
        stage("code"){
            steps{
                echo "This is Execute "
            }
        }
        stage("code"){
            steps{
                echo "end of Code "
            }
        }

    }
}