apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: invoice-generator-namespace
spec:
  accessModes:
    - ReadWriteOnce  # This volume can be mounted as read-write by a single node
  resources:
    requests:
      storage: 10Gi  # Adjust the size as per your requirements
  storageClassName: manual  # Specify the storage class name for dynamic provisioning
  selector:
    matchLabels:
      name: postgresql-pv  # Match the labels of the PersistentVolume (pv.yml)
