apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-external-pv
spec:
  capacity:
    storage: 20Gi  # Adjust the size as per your requirements
  accessModes:
    - ReadWriteOnce  # Access mode (e.g., ReadWriteOnce, ReadWriteMany, ReadOnlyMany)
  persistentVolumeReclaimPolicy: Retain  # Policy for what happens to the volume when released
  storageClassName: external-storage  # Storage class name for dynamic provisioning (if applicable)
  nfs:
    path: /path/to/your/nfs/share  # Path to the NFS share
    server: nfs-server-ip-address  # IP address or hostname of the NFS server

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
spec:
  capacity:
    storage: 20Gi  # Adjust the size as per your requirements
  accessModes:
    - ReadWriteOnce  # Access mode (must match the external PV's access mode)
  persistentVolumeReclaimPolicy: Retain  # Policy for what happens to the volume when released
  storageClassName: external-storage  # Storage class name for dynamic provisioning (if applicable)
  claimRef:
    namespace: invoice-generator-namespace
    name: postgresql-pvc  # Name of the PersistentVolumeClaim to bind to

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: invoice-generator-namespace
spec:
  accessModes:
    - ReadWriteOnce  # Access mode (must match the PV's access mode)
  resources:
    requests:
      storage: 20Gi  # Requested storage size (must not exceed PV's capacity)
  storageClassName: external-storage  # Storage class name matching the PV's class
  volumeName: postgresql-pv  # Name of the PersistentVolume to claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: invoice-generator-namespace
spec:
  accessModes:
    - ReadWriteOnce  # Access mode (must match the PV's access mode)
  resources:
    requests:
      storage: 20Gi  # Requested storage size (must not exceed PV's capacity)
  storageClassName: external-storage  # Storage class name matching the PV's class
  volumeName: postgresql-pv  # Name of the PersistentVolume to claim