apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: invoice-generator-namespace
data:
  nginx.conf: |
    worker_processes  1;
    events {
        worker_connections  1024;
    }
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        sendfile        on;
        keepalive_timeout  65;
        # other nginx configurations
    }
