apiVersion: v1
kind: Pod
metadata:
  name: postgresql-pod
  namespace: invoice-generator-namespace
spec:
  containers:
    - name: postgresql-container
      image: postgres:13
      env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: POSTGRES_PASSWORD
      ports:
        - containerPort: 5432
      volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
        - name: postgresql-config
          mountPath: /etc/postgresql
  volumes:
    - name: postgresql-data
      persistentVolumeClaim:
        claimName: postgresql-pvc
    - name: postgresql-config
      configMap:
        name: postgresql-config-map
