apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
  namespace: invoice-generator-namespace
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: postgresql-container
  template:
    metadata:
      labels:
        app: postgresql-container
    spec:
      containers:
        - name: postgresql-container
          image: postgres:13
      env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
            - name: postgresql-config
              mountPath: /etc/postgresql
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-pvc  # Reference to the PersistentVolumeClaim (pvc.yml)
        - name: postgresql-config
          configMap:
            name: postgresql-config-map  # Reference to the ConfigMap (configmap.yml)
